org: harshitchopde
app: quiz-web-server
service: quiz-server-api

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 20
  region: ap-south-1
  httpApi:
    cors: 
      allowedOrigins:
        - "*"  # Change to "http://localhost:3000" for security
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /{proxy+}  # Wildcard routing for all paths
          method: any

plugins:
  - serverless-offline
